parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: bestnid_db
    database_user: root
    database_password: ~
    locale: es
    secret: 85db95fc9bcbeeb98e34e24fb409fe83
    database_path: null

    mailer_transport: gmail
    mailer_host:      ~
    mailer_user:  wasdinc
    mailer_password:  wasdbestnid
